---
- name: Add bitnami chart repo
  community.kubernetes.helm_repository:
    state: present
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy mongodb
  community.kubernetes.helm:
    state: "{{ mongodb_state }}"
    name: mongodb
    namespace: "{{ namespace }}"
    create_namespace: true
    chart_ref: bitnami/mongodb-sharded
    chart_version: 3.4.4
    values: "{{ lookup('template', 'values.yaml.j2', variable_start_string='[%', variable_end_string='%]') | from_yaml | combine(mongodb_chart_values, recursive=True) }}"
    wait: yes
    wait_timeout: 10m
  register: mongodb_installed
